#!/usr/bin/guile
!#

; the modules directory should be in GUILE_LOAD_PATH, then the following line is not necessary
(add-to-load-path (string-append (getcwd) "/modules"))

(import (sph web app) (project-name))
(swa-start swa-app "default" swa-server-scgi)
