#!/bin/sh

t=$1/usr/share/guile/site
mkdir -p $t
cp -rt $t sph
find $t/sph -type f -exec chmod 644 {} \; &&
find $t/sph -type d -exec chmod 755 {} \;

t=$1/usr/share/sph/web/app
mkdir -p $t
cp -rt $t default-project minimal-project
t=$1/usr/share/sph
find $t -type f -exec chmod 644 {} \; &&
find $t -type d -exec chmod 755 {} \;

t=$1/usr/bin
mkdir -p $t
cp -t $t exec/web-app
chmod 755 $t/web-app
