#!/usr/bin/guile
!#

;depends on "cp" and "sed"

(import (sph) (sph alist) (only (sph one) program-path) (sph filesystem) (sph cli))
(define example-project-path "/usr/share/sph/web/app/example-project")
(define minimal-project-path "/usr/share/sph/web/app/minimal-project")

(define (create-new-project path options)
  (let*
    ( (minimal (alist-ref options (q minimal)))
      (source-path (if minimal minimal-project-path example-project-path)))
    (if (file-exists? source-path)
      (begin (ensure-directory-structure path)
        (let
          (sed-file-paths
            (if minimal
              (begin
                (system* "cp" "--dereference"
                  "--recursive" "--no-target-directory" source-path path)
                (list))
              (begin
                (system* "cp" "--dereference"
                  "--recursive" "--no-target-directory" source-path path)
                (list (string-append path "branch/main.scm")))))
          (apply system* "sed"
            "-i" (string-append "s/project-name/" (basename path) "/g")
            (string-append path "init.scm") sed-file-paths)))
      (throw (q source-path-not-found) source-path))))

(define (web-app options)
  (let (target-path (alist-ref options (q target)))
    (if target-path
      (let (target-path (path->full-path target-path))
        (if (file-exists? target-path) (simple-format #t "fail - \"~A\" exists\n" target-path)
          (begin (create-new-project (ensure-trailing-slash target-path) options)
            (simple-format #t "created ~A\n" target-path))))
      (begin (simple-format #t "please specify a target path or name\n") (exit)))))

(let*
  ( (cli
      (cli-create #:about "creates new (web app) projects"
        #:options
        (ql ((target)) (minimal #\m #f #f #f #f "creates only a minimal project structure"))))
    (options (cli)))
  (if (null? options) (cli (list "--help")) (web-app options)))