#!/usr/bin/guile
!#

(import (sph install))

(install-cli-guile (path-lib-scheme "modules/sph")
  ("/usr/share/sph/web/app" "example/project-example" "example/project-minimal")
  ("/usr/bin" 493 "exe/web-app"))
