#!/usr/bin/env guile
!#

(import (sph install))

(install-cli
  (system-executables 755 "exe/web-app")
  (guile-site-modules "modules/sph")
  ("/usr/share/sph/web/app" "example/project-example" "example/project-minimal"))
