#!/usr/bin/guile
!#

(import (sph install))

(install-cli-guile (path-lib-scheme "modules/sph")
  ("/usr/share/sph/web/app" "other/project-example" "other/project-minimal")
  ("/usr/bin" #o755 "exe/web-app"))
