#!/usr/bin/guile
!#

(import (sph) (sph test))

(define settings
  (test-settings-default-custom
    ;only (q ((test module sph filesystem asset-compiler)))
    path-search "modules" reporter-name (q compact)))

(test-execute-modules-by-prefix #:settings settings (q (test module sph)))
